name: Check Class Availability

on:
  schedule:
    - cron: "1 14,22 * * *" # 6:01 PM, 10:01 EDT Daily
  workflow_dispatch:

jobs:
  check-availability:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Check class availability
        id: check
        env:
          URL: ${{ secrets.URL }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: |
          python check_availability.py

      - name: Log when no classes are available
        if: steps.check.outputs.availability != 'true'
        run: |
          echo "No available classes found today. Will check again tomorrow."

      - name: Create a push request
        if: steps.check.outputs.availability == 'true'
        run: |
          # Get today's date
          TODAY=$(date '+%Y-%m-%d')
          # Create success.txt file with message
          echo "Sign up quick on $TODAY!" > success.txt

          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add success.txt
          git commit -m "Class available on $TODAY"
          git push origin HEAD:main
